import { Comercial } from "./Comercial";
import { Imagen } from "./Imagen";
import { Operacion } from "./Operacion";
import { SueloNave } from "./SueloNave";
import { Vivienda } from "./Vivienda";
import { Address } from "./address";

export interface DetailProperty {
    id: number;
    original_id: string;
    IdUnico: string;
    FkTipo: number;
    FkSubtipo: number;
    ConstructedArea: number;
    PromoReference: string;
    UsableArea: number;
    UrlYoutube: string;
    UrlTourVirtual: string;
    Decorview: string;
    PlanosUrl: string;
    idExternoGestor: number;
    EnergyRating: string;
    SupParcela: number;
    Comercializacion: string;
    RefCatastral: string;
    NumImagen: number;
    LastModifiedDate: Date;
    Patrocinado: number;
    Excent: number;
    Destacado: number;
    Estrenar: number;
    EstadoObra: string;
    Activo: number;
    CampanaEspecial: number;
    DestacadoPromocion: number;
    Imagen: string;
    Relevancy: number;
    servicer: string;
    estadoAlquiler: string;
    posesion: string;
    scoring: string;
    SuperficieTotal: number;
    emailGestorVentaDigital: string;
    nombreGestorVentaDigital: string;
    perimetro: string;
    idTier: number;
    redComercial: string;
    fechaInicioTransparencia: string;
    fechaFinTransparencia: string;
    ventaOnlineExclusiva: number;
    urlVentaExclusiva: string;
    situacionEspecial: string;
    Proindiviso: string;
    PrecioAlquiler: string;
    FechaFinContratoAlquiler: string;
    Particular: number;
    Description: string;
    Metadescription: string;
    provinciaUrl: string;
    ciudadUrl: string;
    Capital: string;
    Ciudad: string;
    gStaticMapImage: string;
    bookingBlocked: number;
    visitBlocked: number;
    originalId: string;
    Campanas: string;
    vivienda: Vivienda;
    comercial: Comercial;
    suelonave: SueloNave;
    address: Address;
    operacion: Operacion;
    imagenes: Imagen[];
}
